server:
  host: 0.0.0.0
  port: 8088
  mode: debug

log:
  level: debug
  format: json
  output: file
  filePath: logs/app.log
  maxAge: 7

database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  db: sanguo_server
  maxOpenConns: 200
  maxIdleConns: 50
  connMaxLifetime: 3600

redis:
  host: 127.0.0.1
  port: 6379
  password: "123456"
  db: 0
  poolSize: 100
